version: "3"
services:
  mongo:
    image: "mongo:3.4"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
